 const initialiser = {
  AUTHORISE_APP: 'AUTHORISE_APP',
  SET_INITIALISER_TASK: 'SET_INITIALISER_TASK',
  NET_STATUS_CHANGED: 'NET_STATUS_CHANGED',
  RECONNECT_APP: 'RECONNECT_APP',
  AUTHORISE_SHARE_MD: 'AUTHORISE_SHARE_MD'
};

export default initialiser;
