const appActions = {
  CREATE_ACCOUNT_RESET: 'CREATE_ACCOUNT_RESET',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_ERROR: 'SET_CREATE_ACCOUNT_ERROR',
  PUSH_MAIL: 'PUSH_MAIL',
  MAIL_PROCESSING: 'MAIL_PROCESSING',
  SET_ACTIVE_MAIL: 'SET_ACTIVE_MAIL',
  CANCEL_COMPOSE: 'CANCEL_COMPOSE',
  PUSH_TO_INBOX: 'PUSH_TO_INBOX',
  PUSH_TO_ARCHIVE: 'PUSH_TO_ARCHIVE',
  FETCH_EMAIL_IDS: 'FETCH_EMAIL_IDS',
  GET_CONFIG: 'GET_CONFIG',
  REFRESH_EMAIL: 'REFRESH_EMAIL',
  STORE_NEW_ACCOUNT: 'STORE_NEW_ACCOUNT'
};

export default appActions;
