platform:
  - x64

image: Visual Studio 2015

environment:
  nodejs_version: "8"
  matrix:
    - NODE_ENV: "prod"
      win_runtime: win-x64
      arch: x64
      plat: win32

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - yarn --version
  - yarn config set child-concurrency 1
  - yarn 
  - yarn add windows-build-tools --global


build_script:
  - node --version
  - yarn --version


before_deploy:
  - ps: >-
        $TOKEN="$env:GITHUB_AUTH_TOKEN";
        $OWNER="MaidSafe";
        $REPO="release_config";
        $REPO_PATH="safe_authenticator/log.toml";
        $FILE="https://api.github.com/repos/$OWNER/$REPO/contents/$REPO_PATH";
        $APP_DIR="$env:APP_PKG_DIR";
        $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]";
        $headers.Add("Authorization", "token $TOKEN");
        $headers.Add("Accept", 'application/vnd.github.v3.raw');
        Invoke-WebRequest -URI $FILE -Headers $headers -OutFile ".\log.toml";
  - yarn install-all
  - yarn package-all
  - echo %APPVEYOR_REPO_TAG%
  - echo %APPVEYOR_REPO_TAG_NAME%
  - ps: Get-ChildItem .\email_app\out\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\web_hosting_manager\release\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\email_app\out\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\web_hosting_manager\release\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }


deploy:
  release: $(appveyor_repo_tag_name)
  tag: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token: $(github_auth_token)
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag:  true        # deploy on tag push only
