export default {
  AUTHORISE_APP: 'AUTHORISE_APP',
  APP_AUTHORISED: 'APP_AUTHORISED',
  RECONNECT_APP: 'RECONNECT_APP',
  AUTHORISE_SHARE_MD: 'AUTHORISE_SHARE_MD',
  MD_AUTHORISED: 'MD_AUTHORISED',
  CANCEL_MD_AUTH_REQ: 'CANCEL_MD_AUTH_REQ',
};
