const ACTION_TYPES = {
  AUTHORISE_APP: 'AUTHORISE_APP',
  GET_CONFIG: 'GET_CONFIG',
  REFRESH_EMAIL: 'REFRESH_EMAIL',
  SET_INITIALIZER_TASK: 'SET_INITIALIZER_TASK',

  // legacy
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_ERROR: 'SET_CREATE_ACCOUNT_ERROR',

  PUSH_MAIL: 'PUSH_MAIL',
  SET_MAIL_PROCESSING: 'SET_MAIL_PROCESSING',
  CLEAR_MAIL_PROCESSING: 'CLEAR_MAIL_PROCESSING',
  SET_ACTIVE_MAIL: 'SET_ACTIVE_MAIL',

  CANCEL_COMPOSE: 'CANCEL_COMPOSE',
  CLEAR_INBOX: 'CLEAR_INBOX',
  PUSH_TO_INBOX: 'PUSH_TO_INBOX'
};

export default ACTION_TYPES;
