export default {
  SET_PUBLIC_NAMES: 'SET_PUBLIC_NAMES',
  SET_SERVICE_CONTAINERS: 'SET_SERVICE_CONTAINERS',
  CREATE_PUBLIC_NAME: 'CREATE_PUBLIC_NAME',
  FETCH_SERVICE_CONTAINERS: 'FETCH_SERVICE_CONTAINERS',
  RESET_SERVICE_CONTAINERS: 'RESET_SERVICE_CONTAINERS',
  REST_PUBLIC_NAMES: 'REST_PUBLIC_NAMES',
  CAN_ACCESS_PUBLIC_NAME: 'CAN_ACCESS_PUBLIC_NAME',
};
