export default {
  FETCH_SERVICES: 'FETCH_SERVICES',
  CHECK_SERVICE_EXIST: 'CHECK_SERVICE_EXIST',
  DELETE_SERVICE: 'DELETE_SERVICE',
  CANCEL_MD_REQ: 'CANCEL_MD_REQ',
  SEND_MD_REQ: 'SEND_MD_REQ',
  MD_AUTHORISED: 'MD_AUTHORISED',
  REMAP_SERVICE: 'REMAP_SERVICE',
};
